name: MessengerApp CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
  BUILD_PATH: ${{github.workspace}}/build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: CMake setup
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.22.1'
    - name: Boost library installation
      run: sudo apt-get update && sudo apt-get install libboost-all-dev -y
    - name: OpenSSL library installation
      run: sudo apt-get update && sudo apt-get install libssl-dev -y
    - name: CMake configuration
      run: cmake -B ${{env.BUILD_PATH}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Project build
      run: cmake --build ${{env.BUILD_PATH}} --config ${{env.BUILD_TYPE}}

    - name: UT
      working-directory: ${{env.BUILD_PATH}}
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
